image: Visual Studio 2019
configuration: Release

environment:
  DOTNET_SKIP_FIRST_TIME_EXPERIENCE: true
  github_token:
    secure: RAU/MUjUsCxEfK5NRX1iFGtna4JHtz3TGQtIrxbYcF+IrVpKC5ceW73RXtfAjVXV

nuget:
  project_feed: true
  disable_publish_on_pr: true

install:
  - ps: |
      Invoke-WebRequest https://github.com/benjamin-hodgson/BuildScripts/archive/master.zip -OutFile BuildScripts.zip
      Expand-Archive BuildScripts.zip -Destination .
      mv BuildScripts-master BuildScripts

  - ps: .\BuildScripts\appveyor\InitBuildNumber.ps1
  - cmd: msbuild Pidgin.sln /t:restore /p:Configuration=%CONFIGURATION% /v:Minimal
  - cmd: cinst docfx
  - ps: .\BuildScripts\appveyor\ConfigureGit.ps1

build:
  project: Pidgin.sln
  verbosity: minimal

after_test:
  - cmd: dotnet run --configuration %CONFIGURATION% --project Pidgin.Bench\Pidgin.Bench.csproj -- -f *
  - cmd: msbuild Pidgin.sln /t:pack /p:Configuration=%CONFIGURATION% /p:IncludeSymbols=true /p:PackageOutputPath=..\nupkgs /v:Minimal
  - cmd: docfx Pidgin.Docs/docfx.json

artifacts:
  - type: NuGetPackage
    path: nupkgs/*.nupkg
  - path: BenchmarkDotNet.Artifacts
  - path: Pidgin.Docs/_site

deploy:
  provider: NuGet
  skip_symbols: false
  api_key:
    secure: jRoXOnbadZODpbg/Hq7NoXf+bURBt1gxlrmKUwhGLKDGIf78URCOIcKUKPzE57x4
  on:
    appveyor_repo_tag: true

on_success:
  - ps: .\BuildScripts\appveyor\PushDocs.ps1
